name: Zhimin Sun
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
           /travels/:year/:month/:day/:title
collections:
  travelposts:
    output: true
  projectposts:
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true